### ISSUE TITLE
Messages cannot be marked as read

### ISSUE THREAD

**Issue by Requinard** [eurofurence/ef-app_android#138]
a bt if an issue that we can not mark messages to be read.

# how to

1. receive a message
2. open message screen
3. read logs

# logs

```
08-13 14:57:30.716 22595-22812/org.eurofurence.connavigator.debug I/FragmentViewMessages: Succesfully retrieved 3 messages
08-13 14:57:30.718 22595-22665/org.eurofurence.connavigator.debug D/NET: Performing request: https://app.eurofurence.org/Api/v2/Communication/PrivateMessages/6b377a13-9b2c-4770-8a35-9fba1dd158a2/Read
08-13 14:57:30.719 22595-22665/org.eurofurence.connavigator.debug E/Volley: [3267] NetworkDispatcher.run: Unhandled exception java.lang.NullPointerException: Attempt to invoke interface method 'void org.apache.http.HttpEntity.writeTo(java.io.OutputStream)' on a null object reference
                                                                            java.lang.NullPointerException: Attempt to invoke interface method 'void org.apache.http.HttpEntity.writeTo(java.io.OutputStream)' on a null object reference
                                                                                at io.swagger.client.request.PostRequest.getBody(PostRequest.java:44)
                                                                                at com.android.volley.toolbox.HurlStack.addBodyIfExists(HurlStack.java:260)
                                                                                at com.android.volley.toolbox.HurlStack.setConnectionParametersForRequest(HurlStack.java:234)
                                                                                at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:107)
                                                                                at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
                                                                                at org.eurofurence.connavigator.webapi.apiService$initialize$1$network$1.performRequest(ApiService.kt:112)
                                                                                at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)
08-13 14:57:30.732 22595-22812/org.eurofurence.connavigator.debug W/System.err: java.util.concurrent.ExecutionException: com.android.volley.VolleyError: java.lang.NullPointerException: Attempt to invoke interface method 'void org.apache.http.HttpEntity.writeTo(java.io.OutputStream)' on a null object reference
08-13 14:57:30.733 22595-22812/org.eurofurence.connavigator.debug W/System.err:     at com.android.volley.toolbox.RequestFuture.doGet(RequestFuture.java:117)
08-13 14:57:30.733 22595-22812/org.eurofurence.connavigator.debug W/System.err:     at com.android.volley.toolbox.RequestFuture.get(RequestFuture.java:97)
08-13 14:57:30.733 22595-22812/org.eurofurence.connavigator.debug W/System.err:     at io.swagger.client.ApiInvoker.invokeAPI(ApiInvoker.java:357)
08-13 14:57:30.733 22595-22812/org.eurofurence.connavigator.debug W/System.err:     at io.swagger.client.api.CommunicationApi.apiV2CommunicationPrivateMessagesByMessageIdReadPost(CommunicationApi.java:96)
08-13 14:57:30.733 22595-22812/org.eurofurence.connavigator.debug W/System.err:     at org.eurofurence.connavigator.ui.FragmentViewMessages$onViewCreated$5.invoke(FragmentViewMessages.kt:89)
08-13 14:57:30.733 22595-22812/org.eurofurence.connavigator.debug W/System.err:     at org.eurofurence.connavigator.ui.FragmentViewMessages$onViewCreated$5.invoke(FragmentViewMessages.kt:37)
08-13 14:57:30.733 22595-22812/org.eurofurence.connavigator.debug W/System.err:     at nl.komponents.kovenant.AbstractPromise$SuccessCallbackContextNode$runSuccess$1.invoke(promises-jvm.kt:650)
08-13 14:57:30.733 22595-22812/org.eurofurence.connavigator.debug W/System.err:     at nl.komponents.kovenant.AbstractPromise$SuccessCallbackContextNode$runSuccess$1.invoke(promises-jvm.kt:647)
08-13 14:57:30.733 22595-22812/org.eurofurence.connavigator.debug W/System.err:     at nl.komponents.kovenant.NonBlockingDispatcher$ThreadContext.run(dispatcher-jvm.kt:327)
08-13 14:57:30.733 22595-22812/org.eurofurence.connavigator.debug W/System.err:     at nl.komponents.kovenant.android.KovenantAndroid$createThreadFactory$1$wrapper$1.run(configuration.kt:97)
08-13 14:57:30.733 22595-22812/org.eurofurence.connavigator.debug W/System.err:     at java.lang.Thread.run(Thread.java:818)
08-13 14:57:30.733 22595-22812/org.eurofurence.connavigator.debug W/System.err: Caused by: com.android.volley.VolleyError: java.lang.NullPointerException: Attempt to invoke interface method 'void org.apache.http.HttpEntity.writeTo(java.io.OutputStream)' on a null object reference
08-13 14:57:30.733 22595-22812/org.eurofurence.connavigator.debug W/System.err:     at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:141)
08-13 14:57:30.733 22595-22812/org.eurofurence.connavigator.debug W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void org.apache.http.HttpEntity.writeTo(java.io.OutputStream)' on a null object reference
08-13 14:57:30.733 22595-22812/org.eurofurence.connavigator.debug W/System.err:     at io.swagger.client.request.PostRequest.getBody(PostRequest.java:44)
08-13 14:57:30.733 22595-22812/org.eurofurence.connavigator.debug W/System.err:     at com.android.volley.toolbox.HurlStack.addBodyIfExists(HurlStack.java:260)
08-13 14:57:30.733 22595-22812/org.eurofurence.connavigator.debug W/System.err:     at com.android.volley.toolbox.HurlStack.setConnectionParametersForRequest(HurlStack.java:234)
08-13 14:57:30.733 22595-22812/org.eurofurence.connavigator.debug W/System.err:     at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:107)
08-13 14:57:30.734 22595-22812/org.eurofurence.connavigator.debug W/System.err:     at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
08-13 14:57:30.734 22595-22812/org.eurofurence.connavigator.debug W/System.err:     at org.eurofurence.connavigator.webapi.apiService$initialize$1$network$1.performRequest(ApiService.kt:112)
08-13 14:57:30.734 22595-22812/org.eurofurence.connavigator.debug W/System.err:     at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)
08-13 14:57:35.699 22595-22642/org.eurofurence.connavigator.debug V/FA: Inactivity, disconnecting from the service
```

**Comment by Requinard** [comment]
Was fixed
