### ISSUE TITLE
App crashes on boot due to jodatime

### ISSUE THREAD

**Issue by Requinard** [eurofurence/ef-app_android#26]
Android version: 4.4
Device: Galaxy S3
Recreation:
- Boot the app with the above specs

Exception:

    java.lang.NoClassDefFoundError: net.danlew.android.joda.ResourceZoneInfoProvider
	at net.danlew.android.joda.JodaTimeAndroid.init(JodaTimeAndroid.java:39)
	at org.eurofurence.connavigator.app.ConnavigatorApplication.onCreate(ConnavigatorApplication.kt:20)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4473)
	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5146)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by lukashaertel** [comment]
You broke it, look at https://github.com/dlew/joda-time-android/issues/69#issuecomment-113940265

**Comment by Requinard** [comment]
At least I'm not the one including a gazillion dependencies >:D

**Comment by lukashaertel** [comment]
@Requinard Just try and remove one, let's see how the application works then, shall we? >:E

**Comment by lukashaertel** [comment]
Fixed in #27
