### ISSUE TITLE
Dealers den images are not showing

### ISSUE THREAD

**Issue by Requinard** [eurofurence/ef-app_android#45]
go to the dealers den and you will see it will load the placeholder image.

Stack trace here:
`05-16 21:17:02.875 6073-6490/org.eurofurence.connavigator E/ImageLoader: UIL doesn't support scheme(protocol) by default [{Endpoint}/ImageData/db1a3597-3fa2-4f1b-bc33-fe788c1c6a9f]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
                                                                         java.lang.UnsupportedOperationException: UIL doesn't support scheme(protocol) by default [{Endpoint}/ImageData/db1a3597-3fa2-4f1b-bc33-fe788c1c6a9f]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
                                                                             at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromOtherSource(BaseImageDownloader.java:280)
                                                                             at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:99)
                                                                             at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.downloadImage(LoadAndDisplayImageTask.java:291)
                                                                             at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryCacheImageOnDisk(LoadAndDisplayImageTask.java:274)
                                                                             at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:230)
                                                                             at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:136)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:818)`

**Comment by lukashaertel** [comment]
[{Endpoint}/ImageData/db1a3597-3fa2-4f1b-bc33-fe788c1c6a9f]
Imma enter that one in my browser and see what happens :V

**Comment by Pinselohrkater** [comment]
Just add logic to replace {Endpoint} with the Endpoint URL - that was the intention. :)

**Comment by lukashaertel** [comment]
@Pinselohrkater was kinda obvious IMO :D

**Comment by Pinselohrkater** [comment]
@lukashaertel Please replace {EndpointUrl} too. Because I eventually want to rename it to that. :)

**Comment by Requinard** [comment]
Yup, it's fixed
